config/routes.rb
FaceBook::Application.routes.draw do
  resources :users
  resources :sessions,   only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]

  root  'static_pages#home'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/profile', to: 'static_pages#profile',   via: 'get'
  match '/wall',    to: 'static_pages#wall', via: 'get'
  match '/login',   to: 'static_pages#login',    via: 'get'
  match '/news_feed', to: 'static_pages#news_feed',   via: 'get'

end

app/models/group.rb
class Group < ActiveRecord::Base
end

app/models/message.rb
class Message < ActiveRecord::Base
end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
  belongs_to :user
  default_scope -> { order('created_at DESC') }
  validates :content, presence: true
  validates :user_id, presence: true
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  belongs_to :friend, class_name: "User"
  validates :friend_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :microposts, dependent: :destroy
  has_many :relationships, foreign_key: "friend_id", dependent: :destroy
=begin  has_many :friend_users, through: :relationships, source: :friend
  has_many :reverse_relationships, foreign_key: "friended_id",
                                   class_name:  "Relationship",
                                   dependent:   :destroy
  has_many :friends, through: :reverse_relationships, source: :follower
=end
  before_save { self.email = email.downcase }
  before_create :create_remember_token
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence:   true,
                    format:     { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, length: { minimum: 6 }
  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.hash(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  def feed
    # This is preliminary. See "Following users" for the full implementation.
    Micropost.where("user_id = ?", id)
  end
  
  def friend?(other_user)
    relationships.find_by(friend_id: other_user.id)
  end

  def friend!(other_user)
    relationships.create!(friend_id: other_user.id , accepted: true)
    other_user.relationships.create!(friend_id: current_user.id, accepted: false)
  end

  def unfriend!(other_user)
    relationships.find_by(friend_id: other_user.id).destroy
    other_user.relationships.find_by(friend_id: current_user.id).destroy
  end


  private

    def create_remember_token
      self.remember_token = User.hash(User.new_remember_token)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :signed_in_user
  before_action :correct_user,   only: :destroy

  def create
    @micropost = current_user.microposts.build(micropost_params)
    if @micropost.save
      flash[:success] = "Your tale is saved"
      #redirect back to current page
      if request.env['PATH_INFO'] == current_user
        redirect_to current_user
      else
        redirect_to root_url
      end
    else
      @feed_items = []
      render 'static_pages/home'
    end
  end

  def destroy
    @micropost.destroy
    redirect_to root_url
  end

  private

    def micropost_params
      params.require(:micropost).permit(:content)
    end

    def correct_user
      @micropost = current_user.microposts.find_by(id: params[:id])
      redirect_to root_url if @micropost.nil?
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_to user
    else
      flash.now[:error] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if signed_in?
      @micropost  = current_user.microposts.build
      @feed_items = current_user.feed.paginate(page: params[:page])
    end
  end

  def help		# this is the controller for the help page
  end

  def profile    # this is the controller for the help page
  end

  def wall    # this is the controller for the help page
  end

  def login   # this is the controller for the help page
  end

  def news_feed    # this is the controller for the help page
  end
  
  #Other pages we will need are
  # Profile
  # Profile Preferences
  # Friends 
  # Books (If we end up getting that far.)
  # Login
  # News feed.
  # Not all of these pages will be static however.

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :signed_in_user, only: [:index, :edit, :update]
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user,     only: :destroy

  def index
    @users = User.paginate(page: params[:page])
  end

  def show
    @user = User.find(params[:id])
    if signed_in?
      @micropost  = current_user.microposts.build
    end
    @microposts = @user.microposts.paginate(page: params[:page])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      sign_in @user
      flash[:success] = "Welcome to BookFace!"
      redirect_to @user
    else
      render 'new'
    end
  end
  
  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_url
  end

 private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation, :quotes, :interests, 
                                   :gender, :hometown)
    end

    # Before filters

=begin function replaced by session helper 
    def signed_in_user
      redirect_to signin_url, notice: "Please sign in." unless signed_in?
    end
=end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end

    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "BookFace"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.hash(remember_token))
    self.current_user = user
  end

  def signed_in?
    !current_user.nil?
  end
  
  def current_user=(user)
    @current_user = user
  end

  def current_user
    remember_token = User.hash(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

  def current_user?(user)
    user == current_user
  end

  def signed_in_user
    unless signed_in?
      store_location
      redirect_to signin_url, notice: "Please sign in."
    end
  end

  def sign_out
    current_user.update_attribute(:remember_token,
                                  User.hash(User.new_remember_token))
    cookies.delete(:remember_token)
    self.current_user = nil
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
  </small>
  <nav>
    <ul>
      <li><%= link_to "Help",    help_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
      <ul class="nav navbar-nav pull-left navbar-logo">
      <li class = "logo"><a href= <%=root_path%> > BookFace </a></li>
      </ul>
      <ul class="nav navbar-nav pull-right">
      <% if signed_in? %>
        <li><%= link_to current_user.name, current_user %></li>
      <%else%>
        <li><a href= <%=signin_path%> >Sign In</a></li>
      <%end%>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">More<b class="caret"></b></a>
        <ul class="dropdown-menu">
          <%if signed_in? %>
          <li><%= link_to "Sign Out", signout_path, method: "delete" %>
          <li><%= link_to "Settings", edit_user_path(current_user) %></li>
          <li><%= link_to "All Users", users_path %></li>
          <%end%>
          <li><a href=<%help_path%>>Help</a></li>
          <li class="divider"></li>
          <li>
            <form class="navbar-form navbar-right" role="search">
              <div class="form-group">
                <input type="text" class="form-control" placeholder="Search">
              
              <button type="submit" class="btn btn-default center">Submit</button>
              </div>
            </form>
          </li>
        </ul>
      </li>
    </ul>
  </div>
</nav>

<!--
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "BookFace", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Help", help_path %></li>
          <% if signed_in? %>
            <li><%= link_to "Users", '#' %></li>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>
-->

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/microposts/_micropost.html.erb
<li>
  <div class="hero-unit">
  <span class="content"><%= micropost.content %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(micropost.created_at) %> ago.
  </span>
  <% if current_user?(micropost.user) %>
    <%= link_to "delete", micropost, method: :delete,
                                     data: { confirm: "You sure?" },
                                     title: micropost.content %>
  <% end %>
  <div class="hero-unit">
</li>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="microposts">
    <%= render partial: 'shared/feed_item', collection: @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_feed_item.html.erb
<li id="<%= feed_item.id %>">
  <div class="hero-unit">
  	<%= link_to gravatar_for(feed_item.user), feed_item.user %>
 	 <span class="user">
  	  <%= link_to feed_item.user.name, feed_item.user %>
 	 </span>
  	<span class="content"><%= feed_item.content %></span>
  	<span class="timestamp">
  	  Posted <%= time_ago_in_words(feed_item.created_at) %> ago.
	</span>
	<% if current_user?(feed_item.user) %>
    <%= link_to "delete", feed_item, method: :delete,
                                     data: { confirm: "You sure?" },
                                     title: feed_item.content %>
  	<% end %>
  </div>
</li>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "Tell us of the happenings in your world!" %>
  </div>
  <%= f.submit "Post", class: "btn btn-large btn-primary" %>
<% end %>

app/views/shared/_user_info.html.erb
<%= gravatar_for current_user%><h1>
  <%= link_to current_user.name, current_user %>
</h1>

<span>
  <%= pluralize(current_user.microposts.count, "post") %>
</span>

app/views/static_pages/help.html.erb
<h1>Help</h1>
<p>
  What do you possibly need help with?
</p>

app/views/static_pages/home.html.erb
<% if signed_in? %>

  <div class="row">
    <aside class="span4">
      <section>
        <%= render 'shared/user_info' %>
      </section>
      <section>
      <div class="hero-unit">
        <%= render 'shared/micropost_form' %>
      </div>
      </section>
    </aside>
    <div class="span8">
      <h3>Tales from distant lands</h3>
      <%= render 'shared/feed' %>
    </div>
  </div>

<% else %>

<div class="center hero-unit hero-main"> 
  <h1>Welcome to BookFace!</h1>
  <div class="rounded-corners">
  	<%= image_tag("BookFace1.jpg", alt:"BookFace", height: 400, width: 400, style: "border-radius: 20px") %>
  </div>
  <h2>
    Bookface is a social networking site for book characters from all 
    corners of Apocrypha. Come wizards, come warriors, come detectives, come witches.
    Come heroes, come pirates, come nobodies, come snitches.  Come in, come in for we 
    have fine tales to spin.
  </h2>

   <%= link_to "Sign Up!", signup_path, class: "btn btn-large btn-primary"%>
</div>

<% end %>

app/views/static_pages/login.html.erb
<h1>login</h1>
<p>
  Stuff
</p>

app/views/static_pages/news_feed.html.erb
<h1>News Feed</h1>
<p>
	News Feed
</p>

app/views/static_pages/profile.html.erb
<h1>StaticPages#profile</h1>
<p>Find me in app/views/static_pages/profile.html.erb</p>

app/views/static_pages/wall.html.erb
<h1>StaticPages#wall</h1>
<p>Find me in app/views/static_pages/wall.html.erb</p>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user%>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
  	| <%= link_to "delete", user, method: :delete, 
  								data: { confirm: "You sure?" } %>
  <%end%>
</li>

app/views/users/edit.html.erb
<% provide(:title, "Edit User") %>
<h1>Update your profile</h1>

<div class="row">
  <div class="span6 offset3">
  <div class="hero-unit">
    <%= gravatar_for @user %>
    <a href="http://gravatar.com/emails">change</a>
    <br>
    <br>
    <br>
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :gender %>
      <%= f.text_field :gender %>

      <%= f.label :quotes %>
      <%= f.text_area :quotes, :cols => "30", :rows => "10" %>

      <%= f.label :interests %>
      <%= f.text_area :interests, :cols => "30", :rows => "10" %>

      <%= f.label :hometown %>
      <%= f.text_field :hometown %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password, "New Password" %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirm New Password" %>
      <%= f.password_field :password_confirmation %>
      <div class = "center">
      <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
      </div>
    <% end %>

    </div>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All Users') %>
<h1>All Users</h1>


<%= will_paginate %>

<ul class="users">
  <% @users.each do |user| %>
  	<div class="hero-unit">
	<%= render user %>
	</div>
  <% end %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign Up') %>

<h1>Sign Up</h1>

<div class="row">
  <div class="span6 offset3">
  <div class="hero-unit">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirm Password" %>
      <%= f.password_field :password_confirmation %>
    <div class="center">
      <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
  </div>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="span4">
    <section>
    <h3 class = "green-links">
        <%= gravatar_for @user %>
        <%= link_to @user.name, user_path %>
    </h3>
    </section>
    <div class="profile hero-unit"><h4>Gender:</h4> <p2><%= @user.gender %></p2>
      <h4>Interests:</h4> <p2><%= @user.interests %><p2> 
      <h4>Quotes:</h4> <p2><%= @user.quotes %><p2> 
      <h4>Hometown:</h4> <p2><%= @user.hometown %><p2>
    </div>
  </aside>
  <div class="span8">
    <% if (@user.microposts.any?)%>
      <%if signed_in? && (current_user == @user)%>
        <section><h3>Spin us a Tale</h3></section>
        <section>
          <%= render 'shared/micropost_form' %>
        </section>
      <% end %>
      <h3>Tales (<%= @user.microposts.count %>)</h3>
      <ol class= "microposts" >
        <%= render @microposts %>
      </ol>
      <%= will_paginate @microposts %>
    <% end %>
  </div>
</div>